### PR TITLE
Remove calls to deprecated methods getDefaultValue and getFilePath

### PR DESCRIPTION
**Pull request by jalogut**

### CODE REVIEW

**Comment by jalogut** [comment]
Could you merge that into master? Thanks

**Comment by jalogut** [comment]
Hello,

Could you give me some feedback about this pull request? Is there anything else I need to change or is it ready for merging?

Regards

**Comment by ghost** [comment]
Hello,
Can u replace this deprecated method by another ? 
The drupal module use this fallback

**Comment by jalogut** [comment]
Hello,

Do you mean the getDefaultValue()??

**Comment by ghost** [comment]
yes

**Comment by jalogut** [comment]
Hi, there is not such a method to replace that. The defaultValue attribute was removed on version 1.3 and after that attributes do not have anything like that. For that reason the default value is always null.

Is that ok for you?

**Comment by ghost** [comment]
It 's ok, thank you ! i merge this branch

**Comment by jalogut** [comment]
Hi, thanks for approving. Do you know when it will be merged in Master?

**Comment by cmefferte** [comment]
Hi,

It's merged !

2015-08-07 9:44 GMT+02:00 Juan Alonso notifications@github.com:

**Pull request merged**
